# Generated by Django 5.1.4 on 2025-09-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Item_itens',
                'permissions': [('detail_item', 'Pode ver o detalhe do item')],
            },
        ),
    ]
