# Generated by Django 5.1.4 on 2025-08-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': [('detail_item', 'Pode ver o detalhe do item')]},
        ),
        migrations.AlterModelTable(
            name='item',
            table='Item_itens',
        ),
    ]
