# Generated by Django 5.1.4 on 2025-08-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_options_alter_item_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
    ]
