# Generated by Django 5.1.4 on 2025-08-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=50)),
                ('raca', models.CharField(max_length=50)),
                ('nivel', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('ouro', models.IntegerField()),
                ('historia', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('Personagem', 'Personagem'), ('Monstro', 'Monstro'), ('NPC', 'NPC')], max_length=50)),
            ],
        ),
    ]
