# Generated by Django 5.1.4 on 2025-09-17 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guilda', '0001_initial'),
        ('item', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPersonagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
            ],
            options={
                'db_table': 'Personagem_itens',
            },
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=50)),
                ('raca', models.CharField(max_length=50)),
                ('nivel', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('ouro', models.IntegerField()),
                ('historia', models.CharField(max_length=500)),
                ('tipo', models.CharField(choices=[('Personagem', 'Personagem'), ('Monstro', 'Monstro'), ('NPC', 'NPC')], max_length=50)),
                ('criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario')),
                ('guilda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guilda.guilda')),
                ('inventario', models.ManyToManyField(related_name='personagens', through='personagem.ItemPersonagem', to='item.item')),
            ],
            options={
                'db_table': 'Personagem_personagens',
                'permissions': [('detail_personagem', 'Pode ver o detalhe do personagem')],
            },
        ),
        migrations.AddField(
            model_name='itempersonagem',
            name='personagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personagem.personagem'),
        ),
    ]
