# Generated by Django 5.1.4 on 2025-08-26 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilda', '0001_initial'),
        ('personagem', '0002_alter_personagem_options'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='criador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='guilda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guilda.guilda'),
        ),
        migrations.AlterModelTable(
            name='personagem',
            table='Personagem_personagens',
        ),
    ]
