# Generated by Django 5.1.4 on 2025-08-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_options_alter_item_table'),
        ('personagem', '0003_personagem_criador_personagem_guilda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='inventario',
            field=models.ManyToManyField(related_name='personagens', to='item.item'),
        ),
    ]
