# Generated by Django 5.1.4 on 2025-08-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0004_personagem_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='historia',
            field=models.CharField(max_length=500),
        ),
    ]
