# Generated by Django 5.1.4 on 2025-08-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guilda',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
    ]
