# Generated by Django 4.2.21 on 2025-09-16 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('concluida', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Missao_missoes',
                'permissions': [('detail_missao', 'Pode ver o detalhe da missao')],
            },
        ),
        migrations.CreateModel(
            name='MissaoPersonagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missao.missao')),
            ],
            options={
                'db_table': 'Missao_personagens',
            },
        ),
    ]
