# Generated by Django 5.1.4 on 2025-09-17 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('concluida', models.BooleanField(default=False)),
                ('recompensa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item')),
            ],
            options={
                'db_table': 'Missao_missoes',
                'permissions': [('detail_missao', 'Pode ver o detalhe da missao')],
            },
        ),
        migrations.CreateModel(
            name='MissaoPersonagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missao.missao')),
            ],
            options={
                'db_table': 'Missao_personagens',
            },
        ),
    ]
