# Generated by Django 5.1.4 on 2025-09-17 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missao', '0001_initial'),
        ('personagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missaopersonagem',
            name='personagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personagem.personagem'),
        ),
        migrations.AddField(
            model_name='missao',
            name='personagens',
            field=models.ManyToManyField(related_name='missoes', through='missao.MissaoPersonagem', to='personagem.personagem'),
        ),
    ]
