# Generated by Django 4.2.21 on 2025-09-16 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missao', '0001_initial'),
        ('personagem', '0001_initial'),
        ('item', '0003_alter_item_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='missaopersonagem',
            name='personagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personagem.personagem'),
        ),
        migrations.AddField(
            model_name='missao',
            name='personagens',
            field=models.ManyToManyField(related_name='missoes', through='missao.MissaoPersonagem', to='personagem.personagem'),
        ),
        migrations.AddField(
            model_name='missao',
            name='recompensa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item'),
        ),
    ]
