# Generated by Django 5.1.4 on 2025-08-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missao', '0002_alter_missao_options_alter_missao_table'),
        ('personagem', '0003_personagem_criador_personagem_guilda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missao',
            name='concluida',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False),
        ),
        migrations.AddField(
            model_name='missao',
            name='personagens',
            field=models.ManyToManyField(related_name='missoes', to='personagem.personagem'),
        ),
    ]
