# Generated by Django 5.1.4 on 2025-08-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missao', '0003_missao_concluida_missao_personagens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missao',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
    ]
